### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by Alextheabest** [Anonym0usWork1221/C-Android-Memory-Tool#2]
Can you implement for non rooted devices like loading the library from the game

**Comment by Anonym0usWork1221** [comment]
You can create a compiled .so file and place it in virtual environment root
direct then execute it that will work fine for non root.

**Comment by Alextheabest** [comment]
Yes I can create .so file and execute in virtual but virtual space itself is big and make the game and performance lag. What about a way to directly loading the .so file in the game apk and  load from it without root and virtual they say "inbuilt"

Structure
App/lib/arch/native-lib.so

In Smali
```smali
const-string v0, "native-lib"

invoke-static {v0}, Ljava/lang/System;->loadLibrary(Ljava/lang/String;)V
```

**Comment by Anonym0usWork1221** [comment]
If you are trying to create a mod menu, you need to import the .cpp file
instead of the .h file. I am not sure about the exact issue, but some
people are facing problems when loading the header file. However, in a mod
menu, importing the memory tool should work fine since it will be injected
into the game and reading its files should not be an issue.
